version: '3.8'

services:
  varcavia:
    build:
      context: .
      target: runtime
    container_name: varcavia-app
    ports:
      - "3000:3000"
    volumes:
      - ./indexed:/app/indexed
      - ./parsed:/app/parsed
      - ./public:/app/public
    environment:
      - NODE_ENV=production
    command: ["node", "src/api.js"]
    restart: unless-stopped
