name: varcavia-core
region: fra1

services:
  - name: api
    github:
      repo: VARCAVIA/core
      branch: main
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NODE_ENV
        value: production
