name: Deploy to DigitalOcean App Platform

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy image from Docker Hub
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}
          project_id: ${{ secrets.DO_PROJECT_ID }}
          app_spec_location: .do/app.yaml
          # app_name rimosso -> crea nuova app se non esiste
