name: Frontend CI + Vercel Deploy

on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4            # clone repo :contentReference[oaicite:0]{index=0}
      - uses: actions/setup-node@v4           # install Node 20 :contentReference[oaicite:1]{index=1}
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci                           # install deps
      - run: npm run build                    # vite build
      - uses: actions/upload-artifact@v4      # attach dist folder :contentReference[oaicite:2]{index=2}
        with:
          name: frontend-dist
          path: frontend/dist

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
      - name: Deploy to Vercel                # CLI action verso Vercel :contentReference[oaicite:3]{index=3}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend
          vercel-args: "--prod --confirm --env VITE_API_URL=${{ secrets.VITE_API_URL }}"
